### ISSUE TITLE
Suddenly getting Less::Error: 'font-awesome.less' wasn't found when precompiling

### ISSUE THREAD

**Issue by jarrettgreen** [FortAwesome/font-awesome-less#9]
This started randomly.

`gem 'font-awesome-less', '~> 4.2.0'`
`@import 'font-awesome';`

**Comment by NilAndNull** [comment]
I'm having this issue too:

```
ActionView::Template::Error ('font-awesome-sprockets.less' wasn't found
  (in /nilandnull/app/assets/stylesheets/core/_icons.less)):
```

Basically this gem is broken for Rails 4.2. You can't import. I think it might be an issue of less-rails gem but still, LESS support for Rails is bad, I think I might have to switch to SCSS...

**Comment by michaelachrisco** [comment]
@NilAndNull What version was the gem working for you? Rails 4.1? Might have to do a hard set on Rails until the gem is fixed/updated.

**Comment by NilAndNull** [comment]
Rails 4.2
